import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';

interface AddSiteFormProps {
  onSiteAdded: () => void;
}

export function AddSiteForm({ onSiteAdded }: AddSiteFormProps) {
  const [newSite, setNewSite] = useState({ name: '', domain: '' });
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();

  const addSite = async () => {
    if (!newSite.name.trim() || !newSite.domain.trim()) {
      toast({
        title: "⚠️ Error",
        description: "Please fill in both name and domain",
        variant: "destructive"
      });
      return;
    }

    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('sites')
        .insert({
          site_name: newSite.name,
          domain: newSite.domain,
          user_id: user?.id || '',
          tracking_id: '', // Will be auto-generated by trigger
          is_active: true,
          ga_integration_enabled: false,
          ga_enhanced_ecommerce: false,
          ip_exclusion_enabled: true,
          cookie_scanning_enabled: true,
          auto_categorize_cookies: true,
          ga_sync_events: [],
          excluded_ips: [],
          conversion_goals: [],
          screenshot_urls: {},
          navigation_config: {},
          form_tracking_config: {}
        })
        .select()
        .maybeSingle();

      if (error) {
        console.error('Supabase error:', error);
        throw error;
      }

      if (!data) {
        throw new Error('No data returned from the database');
      }

      toast({
        title: "✅ Website added!",
        description: `${data.site_name} - Tracking ID: ${data.tracking_id}`,
      });

      setNewSite({ name: '', domain: '' });
      onSiteAdded();
    } catch (error: any) {
      console.error('Error adding site:', error);
      let errorMessage = "Could not add website";
      
      if (error?.message) {
        errorMessage += `: ${error.message}`;
      }
      
      toast({
        title: "❌ Error",
        description: errorMessage,
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Add website</CardTitle>
        <CardDescription>Set up tracking for a new website</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <Label htmlFor="siteName">Website name</Label>
            <Input
              id="siteName"
              value={newSite.name}
              onChange={(e) => setNewSite({ ...newSite, name: e.target.value })}
              placeholder="My Website"
            />
          </div>
          <div>
            <Label htmlFor="domain">Domain</Label>
            <Input
              id="domain"
              value={newSite.domain}
              onChange={(e) => setNewSite({ ...newSite, domain: e.target.value })}
              placeholder="www.example.com"
            />
          </div>
        </div>
        <Button onClick={addSite} disabled={isLoading}>
          {isLoading ? 'Adding...' : 'Add website'}
        </Button>
      </CardContent>
    </Card>
  );
}